# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8199f977-f86c-4750-8708-409815e5e868";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8199f977-f86c-4750-8708-409815e5e868".device = "/dev/disk/by-uuid/8199f977-f86c-4750-8708-409815e5e868";
  boot.initrd.luks.devices."luks-8541dd24-9ff7-468c-a0d9-6c2237a007c3".device = "/dev/disk/by-uuid/8541dd24-9ff7-468c-a0d9-6c2237a007c3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C532-CE37";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8541dd24-9ff7-468c-a0d9-6c2237a007c3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
